version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: exchange
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/exchange:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/exchange"
      APP_URL: "http://exchange.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "89f8aaa6d247f6af93e7da18b9a88b1b"
      APP_HOSTNAME: "exchange.local"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
      CURRENCY_BEACON_API_KEY: "LAhNhf7Hz2H3SHKCdyx2bIUtCpi2lTNR"
      CURRENCY_BEACON_API_URL: "https://api.currencybeacon.com/v1/"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/exchange:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: