min_max_rate:
    path: /exchange/list
    controller: 'Exchange\Application\Controller\CurrencyController::minMaxRate'
    methods: ['GET', 'POST']

convert_rate:
    path: /exchange/convert
    controller: 'Exchange\Application\Controller\CurrencyController::convertRate'
    methods: ['GET', 'POST']
